apiVersion: v1
data:
  MOSPARO_ENABLE_CRON: "0"
  MOSPARO_ENABLE_WEBSERVER: "1"
kind: ConfigMap
metadata:
  annotations:
    katenary.v3/compose-hash: f7e37491abe3220deeb5961e7dd0075983ee7cb0
    katenary.v3/version: develop-4367a01
  labels:
    {{- include "mosparo.labels" . | nindent 4 }}
    katenary.v3/component: mosparoweb
  name: '{{ include "mosparo.fullname" . }}-mosparoweb'
# vim: ft=helm.gotmpl.yaml