apiVersion: v1
data:
  MYSQL_DATABASE: mosparo
  MYSQL_USER: mosparo
kind: ConfigMap
metadata:
  annotations:
    katenary.v3/compose-hash: f7e37491abe3220deeb5961e7dd0075983ee7cb0
    katenary.v3/version: develop-4367a01
  labels:
    {{- include "mosparo.labels" . | nindent 4 }}
    katenary.v3/component: db
  name: '{{ include "mosparo.fullname" . }}-db'
# vim: ft=helm.gotmpl.yaml